name = "biosugar0-com"
compatibility_date = "2026-02-08"

[assets]
directory = "biosugar0/public"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"

# Production環境: カスタムドメイン
[env.production]
name = "biosugar0-com"
workers_dev = false
preview_urls = false

[[env.production.routes]]
pattern = "www.biosugar0.com"
custom_domain = true

# Dev環境: workers.dev
[env.dev]
name = "biosugar0-com-dev"
workers_dev = true
preview_urls = true
