baseurl = "https://www.biosugar0.com/"
languageCode = "ja"
DefaultContentLanguage = "ja"
theme = "hugo-theme-hello-friend-ng"
title = "biosugar0"
homeSubtitle = "Hello World !"
readOtherPosts = "Read other posts"
copyright = "All rights reserved."



rssLimit  = 10  # Maximum number of items in the RSS feed.
PygmentsCodeFences = true
PygmentsStyle = "monokai"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = false

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:slug/"

[author]
  name = "Yuto Kimura"

[blackfriday]
  hrefTargetBlank = true

[params]
  ganalytics = "UA-155074285-1"
  gitUrl = "https://github.com/biosugar0/biosugar0.com"
  # Metadata mostly used in document's head
  description = "Homepage and blog by biosugar0"
  keywords = "homepage, blog, development, programming, Vim, Go, AWS, Software, Engeneer, エンジニア, プログラミング"

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"
  username = "biosugar0"
  highlightColor = "#2189c8"
  opengraph = true
  images = ["/images/biosugar0.png"]
  amazonTag = ""

[params.favicon.color]
mask = "#252627"
msapplication = "#252627"
theme = "#252627"

# Social icons
[[params.social]]
name = "twitter"
url  = "https://twitter.com/biosugar0"

[[params.social]]
name = "github"
url  = "https://github.com/biosugar0"
[params.logo]
    logoText = "$cd /home/biosugar0"
    logoHomeLink = "/"
    logoColor = "#2189c8"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "posts"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "bookshelf"
    name       = "BookShelf"
    url        = "/bookshelf"
  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags"
